CREATE TABLE groupOfStudent
(
    id   BIGINT generated by default as identity not null,
    NAME VARCHAR(50)                             not null unique,
    constraint PK_GROUP primary key (id)
);

create table IF NOT EXISTS student
(
    id       BIGINT generated by default as identity not null,
    group_id BIGINT                                  not null,
    NAME     VARCHAR(50)                             not null unique,
    constraint PK_ACTOR primary key (id),
    foreign key (group_id) REFERENCES groupOfStudent (id) ON DELETE CASCADE
);

CREATE TABLE teacher
(
    id   BIGINT generated by default as identity not null,
    name VARCHAR(50)                             not null unique,
    constraint PK_TEACHER primary key (id)
);

CREATE TABLE teacherAndGroupOfStudent
(
    id_teacher        BIGINT,
    id_groupOfStudent BIGINT,
    constraint PK_RELATIONSHIP primary key (id_teacher, id_groupOfStudent),
    FOREIGN KEY (id_teacher) REFERENCES teacher (id) ON DELETE CASCADE,
    FOREIGN KEY (id_groupOfStudent) REFERENCES groupOfStudent (id) ON DELETE CASCADE
);